### ISSUE TITLE
We cannot track users through their journey without searching through logs

### ISSUE THREAD

**Issue by andy-paine** [alphagov/verify-matching-service-adapter#30]
There is no way for us to follow a user through a journey without us just looking through MSA logs. The VSP sends the request ID together with the AuthnRequest SAML but to corrolate this to an MSA request, all we can do is check the logs. This makes it difficult to provide any metrics on things like matching, journey times or success rates. Consider adding the request ID to the JSON requests the MSA makes to the local matching service in some way.

**Comment by owenblacker** [comment]
This repo is only temporarily unarchived in order to clean up some Terraform; this issue is no longer pertinent.
